name: MSBuild 17.4

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3
    
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1
        with:
          #vs-version: '[17.4,17.5)'
          msbuild-architecture: x64
          
      - name: Restore NuGet packages
        run: msbuild ConsoleApp\ConsoleApp.sln -t:restore -property:Configuration=Release
          
      - name: Build app for release
        run: msbuild ConsoleApp\ConsoleApp.sln -t:rebuild -property:Configuration=Release

    
